name: Build and scan ROCKs, save and send scan reports

on:
  workflow_dispatch:
  #schedule:
  # every day at 1:12AM UTC
  #- cron: '12 1 * * *'

jobs:
  build-scan-rocks:
    runs-on: ubuntu-20.04
    name: Build and scan ROCKs
    strategy:
      matrix:
        rock:
          - centraldashboard
          - jupyter-pytorch-full
          - notebook-controller
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install tools
        run: |
          ./tools/install-tools.sh
      - name: Build ROCK
        uses: canonical/craft-actions/rockcraft-pack@main
        with:
          path: ${{ matrix.rock }}
      - name: Scan for vulnerabilities
        run: |
          ../tools/scan.sh
        working-directory: ${{ matrix.rock }}
      - name: Send vulnerability records
        run: |
          ../tools/send-scan.sh ./trivy-reports ${{ secrets.JIRA_URL }}
        working-directory: ${{ matrix.rock }}
      - name: Prepare artifacts
        run: |
          tar zcvf trivy-reports-${{ matrix.rock }}.${{ strategy.job-index }}.tar.gz ./trivy-reports
        working-directory: ${{ matrix.rock }}
      - name: Upload Trivy reports
        uses: actions/upload-artifact@v3
        with:
          name: trivy-reports-${{ matrix.rock }}
          path: trivy-reports-${{ matrix.rock }}.${{ strategy.job-index }}.tar.gz

